# Yazi keymap configuration
# Docs: https://yazi-rs.github.io/docs/configuration/keymap

[[manager.prepend_keymap]]
on = ["g", "h"]
run = "cd ~"
desc = "Go to home directory"

[[manager.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/.config"
desc = "Go to config directory"

[[manager.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Developer"
desc = "Go to Developer directory"

[[manager.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/Downloads"
desc = "Go to Downloads directory"

[[manager.prepend_keymap]]
on = ["g", "t"]
run = "cd ~/Desktop"
desc = "Go to Desktop directory"

[[manager.prepend_keymap]]
on = ["g", "."]
run = "cd ~/.config"
desc = "Go to dotfiles"

[[manager.prepend_keymap]]
on = ["<C-h>"]
run = "hidden toggle"
desc = "Toggle hidden files"

[[manager.prepend_keymap]]
on = ["<C-s>"]
run = "shell '$SHELL' --block --confirm"
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["Y"]
run = "copy path"
desc = "Copy file path"

[[manager.prepend_keymap]]
on = ["<C-y>"]
run = "unyank"
desc = "Cancel yank"

[[manager.prepend_keymap]]
on = ["<C-n>"]
run = "create"
desc = "Create file/directory"

[[manager.prepend_keymap]]
on = ["e"]
run = "shell '$EDITOR \"$0\"' --block --confirm"
desc = "Edit file in $EDITOR"

[[manager.prepend_keymap]]
on = ["E"]
run = "shell 'code \"$0\"' --confirm"
desc = "Open in VS Code"

[[manager.prepend_keymap]]
on = ["<C-g>"]
run = "shell 'lazygit' --block --confirm"
desc = "Open lazygit"

[[manager.prepend_keymap]]
on = ["T"]
run = "shell 'trash \"$@\"' --confirm"
desc = "Move to trash"

[[manager.prepend_keymap]]
on = ["z"]
run = "plugin zoxide"
desc = "Jump with zoxide"

[[manager.prepend_keymap]]
on = ["F"]
run = "plugin fzf"
desc = "Find with fzf"
